#!/bin/bash
set -e

PACKAGE_VERSION=$(cat README.md | grep -i --after-context 2 "platform version" | tail -1)
echo Add version tag using $PACKAGE_VERSION

docker tag $IMAGE_NAME $DOCKER_REPO:$PACKAGE_VERSION
docker push $DOCKER_REPO:$PACKAGE_VERSION